name: Update DB
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
    schedule:
        - cron: "*/30 * * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Python 3.13
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"
            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run update-db.py
              run: python update-db.py
            - name: Commit files and push changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git fetch origin
                  git checkout main
                  git add -A
                  git diff --cached --quiet || git commit -m "Updated blocklists"
                  git push origin HEAD:auto-update --force
